// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TippPlattform.Models;

#nullable disable

namespace TippPlattform.Migrations
{
    [DbContext(typeof(TippPlattformContext))]
    partial class TippPlattformContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TippPlattform.Models.Beitritt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("joined_at");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<int>("TippgruppeId")
                        .HasColumnType("int")
                        .HasColumnName("tippgruppe_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("beitritte_pkey");

                    b.HasIndex("TippgruppeId");

                    b.HasIndex("UserId");

                    b.ToTable("beitritte", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiLigaId")
                        .HasColumnType("int")
                        .HasColumnName("api_liga_id");

                    b.Property<string>("LigaName")
                        .HasColumnType("character varying(255)")
                        .HasColumnName("liga_name");

                    b.HasKey("Id")
                        .HasName("liga_pkey");

                    b.ToTable("liga", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.Mannschaft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("APIMannschaftID")
                        .HasColumnType("int")
                        .HasColumnName("api_mannschaft_id");

                    b.Property<int?>("LigaId")
                        .HasColumnType("int")
                        .HasColumnName("liga_id");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("Rang")
                        .HasColumnType("int")
                        .HasColumnName("rang");

                    b.HasKey("Id")
                        .HasName("mannschaft_pkey");

                    b.HasIndex("LigaId");

                    b.ToTable("mannschaft", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.Nachricht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EingeladeneGruppeId")
                        .HasColumnType("int");

                    b.Property<int>("EmpfaengerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GelesenDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nachrichtentext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpfaengerId");

                    b.HasIndex("SenderId");

                    b.ToTable("Nachrichten");
                });

            modelBuilder.Entity("TippPlattform.Models.PunkteRegel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Beschreibung");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Name");

                    b.Property<int>("Quote1")
                        .HasColumnType("int")
                        .HasColumnName("Quote1");

                    b.Property<int>("Quote2")
                        .HasColumnType("int")
                        .HasColumnName("Quote2");

                    b.Property<int>("Quote3")
                        .HasColumnType("int")
                        .HasColumnName("Quote3");

                    b.Property<int>("Quote4")
                        .HasColumnType("int")
                        .HasColumnName("Quote4");

                    b.Property<int>("Tippgruppe_Id")
                        .HasColumnType("int")
                        .HasColumnName("Tippgruppe_Id");

                    b.HasKey("Id")
                        .HasName("PK_PunkteRegel");

                    b.HasIndex("Tippgruppe_Id");

                    b.ToTable("PunkteRegel", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.Spiele", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("APISpielID")
                        .HasColumnType("int")
                        .HasColumnName("api_spiel_id");

                    b.Property<int?>("LigaId")
                        .HasColumnType("int")
                        .HasColumnName("liga_id");

                    b.Property<DateTime?>("SpielBeginn")
                        .HasColumnType("datetime")
                        .HasColumnName("spiel_beginn");

                    b.Property<DateTime?>("SpielEnde")
                        .HasColumnType("datetime")
                        .HasColumnName("spiel_ende");

                    b.Property<int?>("Spieltag")
                        .HasColumnType("int");

                    b.Property<int>("TeamAId")
                        .HasColumnType("integer")
                        .HasColumnName("teamAId");

                    b.Property<int?>("TeamAScore")
                        .HasColumnType("int")
                        .HasColumnName("teama_score");

                    b.Property<int>("TeamBId")
                        .HasColumnType("integer")
                        .HasColumnName("teamBId");

                    b.Property<int?>("TeamBScore")
                        .HasColumnType("int")
                        .HasColumnName("teamb_score");

                    b.HasKey("Id")
                        .HasName("spiele_pkey");

                    b.HasIndex("LigaId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.ToTable("spiele", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.SpieleInTippgruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PunkteRegelId")
                        .HasColumnType("int")
                        .HasColumnName("punkteregel_id");

                    b.Property<int>("SpielId")
                        .HasColumnType("int")
                        .HasColumnName("spiel_id");

                    b.Property<int>("TippgruppeId")
                        .HasColumnType("int")
                        .HasColumnName("tippgruppe_id");

                    b.HasKey("Id")
                        .HasName("spiele_in_tippgruppe_pkey");

                    b.HasIndex("PunkteRegelId");

                    b.HasIndex("SpielId");

                    b.HasIndex("TippgruppeId");

                    b.ToTable("spiele_in_tippgruppe", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.Sporttype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("sporttypes_pkey");

                    b.ToTable("sporttypes", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.Tippgruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("character varying(255)")
                        .HasColumnName("beschreibung");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Passwort")
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwort");

                    b.Property<int>("SporttypeId")
                        .HasColumnType("int")
                        .HasColumnName("sporttype_id");

                    b.HasKey("Id")
                        .HasName("tippgruppen_pkey");

                    b.HasIndex("SporttypeId");

                    b.ToTable("tippgruppen", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.TippgruppeAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TippgruppeId")
                        .HasColumnType("int")
                        .HasColumnName("tippgruppe_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("tippgruppe_admin_pkey");

                    b.HasIndex("TippgruppeId");

                    b.HasIndex("UserId");

                    b.ToTable("tippgruppe_admin", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.Tippschein", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("PaidOut")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Quote1")
                        .HasColumnType("int")
                        .HasColumnName("quote1");

                    b.Property<int>("Quote2")
                        .HasColumnType("int")
                        .HasColumnName("quote2");

                    b.Property<int>("Quote3")
                        .HasColumnType("int")
                        .HasColumnName("quote3");

                    b.Property<int>("Quote4")
                        .HasColumnType("int")
                        .HasColumnName("quote4");

                    b.Property<int>("SpielId")
                        .HasColumnType("int")
                        .HasColumnName("spiel_id");

                    b.Property<int>("TippA")
                        .HasColumnType("int")
                        .HasColumnName("tipp_a");

                    b.Property<int>("TippB")
                        .HasColumnType("int")
                        .HasColumnName("tipp_b");

                    b.Property<int>("TippgruppeId")
                        .HasColumnType("int")
                        .HasColumnName("tippgruppe_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("tippscheine_pkey");

                    b.HasIndex("SpielId");

                    b.HasIndex("TippgruppeId");

                    b.HasIndex("UserId");

                    b.ToTable("tippscheine", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Geburtstag")
                        .HasColumnType("datetime")
                        .HasColumnName("geburtstag");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TippPlattform.Models.Beitritt", b =>
                {
                    b.HasOne("TippPlattform.Models.Tippgruppe", "Tippgruppe")
                        .WithMany("Beitrittes")
                        .HasForeignKey("TippgruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("beitritte_tippgruppe_id_fkey");

                    b.HasOne("TippPlattform.Models.User", "User")
                        .WithMany("Beitrittes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("beitritte_user_id_fkey");

                    b.Navigation("Tippgruppe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TippPlattform.Models.Mannschaft", b =>
                {
                    b.HasOne("TippPlattform.Models.Liga", "Liga")
                        .WithMany("Mannschafts")
                        .HasForeignKey("LigaId")
                        .HasPrincipalKey("ApiLigaId")
                        .HasConstraintName("mannschaft_liga_id_fkey");

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("TippPlattform.Models.Nachricht", b =>
                {
                    b.HasOne("TippPlattform.Models.User", "Empfaenger")
                        .WithMany()
                        .HasForeignKey("EmpfaengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TippPlattform.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empfaenger");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TippPlattform.Models.PunkteRegel", b =>
                {
                    b.HasOne("TippPlattform.Models.Tippgruppe", "Tippgruppe")
                        .WithMany("PunkteRegeln")
                        .HasForeignKey("Tippgruppe_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tippgruppe_punkteregeln_id_fkey");

                    b.Navigation("Tippgruppe");
                });

            modelBuilder.Entity("TippPlattform.Models.Spiele", b =>
                {
                    b.HasOne("TippPlattform.Models.Liga", "Liga")
                        .WithMany("Spieles")
                        .HasForeignKey("LigaId")
                        .HasPrincipalKey("ApiLigaId")
                        .HasConstraintName("spiele_liga_id_fkey");

                    b.HasOne("TippPlattform.Models.Mannschaft", "TeamA")
                        .WithMany("HomeMatches")
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("spiele_teamAId_fkey");

                    b.HasOne("TippPlattform.Models.Mannschaft", "TeamB")
                        .WithMany("AwayMatches")
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("spiele_teamBId_fkey");

                    b.Navigation("Liga");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("TippPlattform.Models.SpieleInTippgruppe", b =>
                {
                    b.HasOne("TippPlattform.Models.PunkteRegel", "PunkteRegel")
                        .WithMany("SpieleInTippgruppe")
                        .HasForeignKey("PunkteRegelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("spiele_in_tippgruppe_punkteregel_id_fkey");

                    b.HasOne("TippPlattform.Models.Spiele", "Spiel")
                        .WithMany("SpieleInTippgruppes")
                        .HasForeignKey("SpielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("spiele_in_tippgruppe_spiel_id_fkey");

                    b.HasOne("TippPlattform.Models.Tippgruppe", "Tippgruppe")
                        .WithMany("SpieleInTippgruppes")
                        .HasForeignKey("TippgruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("spiele_in_tippgruppe_tippgruppe_id_fkey");

                    b.Navigation("PunkteRegel");

                    b.Navigation("Spiel");

                    b.Navigation("Tippgruppe");
                });

            modelBuilder.Entity("TippPlattform.Models.Tippgruppe", b =>
                {
                    b.HasOne("TippPlattform.Models.Sporttype", "Sporttype")
                        .WithMany("Tippgruppens")
                        .HasForeignKey("SporttypeId")
                        .IsRequired()
                        .HasConstraintName("tippgruppen_sporttype_id_fkey");

                    b.Navigation("Sporttype");
                });

            modelBuilder.Entity("TippPlattform.Models.TippgruppeAdmin", b =>
                {
                    b.HasOne("TippPlattform.Models.Tippgruppe", "Tippgruppe")
                        .WithMany("TippgruppeAdmins")
                        .HasForeignKey("TippgruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tippgruppe_admin_tippgruppe_id_fkey");

                    b.HasOne("TippPlattform.Models.User", "User")
                        .WithMany("TippgruppeAdmins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tippgruppe_admin_user_id_fkey");

                    b.Navigation("Tippgruppe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TippPlattform.Models.Tippschein", b =>
                {
                    b.HasOne("TippPlattform.Models.Spiele", "Spiel")
                        .WithMany("Tippscheines")
                        .HasForeignKey("SpielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tippscheine_spiel_id_fkey");

                    b.HasOne("TippPlattform.Models.Tippgruppe", "Tippgruppe")
                        .WithMany("Tippscheines")
                        .HasForeignKey("TippgruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tippscheine_tippgruppe_id_fkey");

                    b.HasOne("TippPlattform.Models.User", "User")
                        .WithMany("Tippscheines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tippscheine_user_id_fkey");

                    b.Navigation("Spiel");

                    b.Navigation("Tippgruppe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TippPlattform.Models.Liga", b =>
                {
                    b.Navigation("Mannschafts");

                    b.Navigation("Spieles");
                });

            modelBuilder.Entity("TippPlattform.Models.Mannschaft", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");
                });

            modelBuilder.Entity("TippPlattform.Models.PunkteRegel", b =>
                {
                    b.Navigation("SpieleInTippgruppe");
                });

            modelBuilder.Entity("TippPlattform.Models.Spiele", b =>
                {
                    b.Navigation("SpieleInTippgruppes");

                    b.Navigation("Tippscheines");
                });

            modelBuilder.Entity("TippPlattform.Models.Sporttype", b =>
                {
                    b.Navigation("Tippgruppens");
                });

            modelBuilder.Entity("TippPlattform.Models.Tippgruppe", b =>
                {
                    b.Navigation("Beitrittes");

                    b.Navigation("PunkteRegeln");

                    b.Navigation("SpieleInTippgruppes");

                    b.Navigation("TippgruppeAdmins");

                    b.Navigation("Tippscheines");
                });

            modelBuilder.Entity("TippPlattform.Models.User", b =>
                {
                    b.Navigation("Beitrittes");

                    b.Navigation("TippgruppeAdmins");

                    b.Navigation("Tippscheines");
                });
#pragma warning restore 612, 618
        }
    }
}
